name: Update Index HTML
on:
  push:
    paths:
      - '**/*.ps1'  # Triggers on PowerShell script changes
    branches:
      - main

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Update index.html
        run: |
          python .github/scripts/update_index.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: 'true'

      - name: Check for changes
        id: check_changes
        run: |
          git status
          git diff index.html

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.html
          git commit -m "Auto-update index.html with new scripts" || echo "No changes to commit"
          git push || echo "No changes to push"
